/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Optional;
import com.example.ProyectoRedFlix.Repositorios.PeliculaRepositorio;
import com.example.ProyectoRedFlix.ProyectoRedFlixApplication;
import com.example.ProyectoRedFlix.SpringContext;
import com.example.ProyectoRedFlix.modelos.Pelicula;

/**
 *
 * @author earm5
 */
public class PeliculaVista extends javax.swing.JFrame {

    /**
     * Creates new form PeliculaVista
     */
    PeliculaRepositorio pel;

    public PeliculaVista() {
        initComponents();
        String[] args = {};
        ProyectoRedFlixApplication.ServerSpring(args);
        pel = SpringContext.getBean(PeliculaRepositorio.class);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonBuscarPelicula = new javax.swing.JButton();
        botonEliminarPelicula = new javax.swing.JButton();
        botonCrearPelicula = new javax.swing.JButton();
        botonActualizarPelicula = new javax.swing.JButton();
        botonLimpiarCampos = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jLabelidPelicula = new javax.swing.JLabel();
        jLabelidAnio = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabelidResumen = new javax.swing.JLabel();
        jTextFieldIdPelicula = new javax.swing.JTextField();
        TextFieldDirector = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextAnio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonBuscarPelicula.setText("Buscar por Id");
        botonBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPeliculaActionPerformed(evt);
            }
        });

        botonEliminarPelicula.setText("Eliminar");
        botonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPeliculaActionPerformed(evt);
            }
        });

        botonCrearPelicula.setText("Crear");
        botonCrearPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPeliculaActionPerformed(evt);
            }
        });

        botonActualizarPelicula.setText("Actualizar");
        botonActualizarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPeliculaActionPerformed(evt);
            }
        });

        botonLimpiarCampos.setText("Limpiar Campos");
        botonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarCamposActionPerformed(evt);
            }
        });

        jLabelidPelicula.setText("ID Película");

        jLabelidAnio.setText("Año");

        jLabelTitulo.setText("Título");

        jLabelDirector.setText("Director");

        jLabelidResumen.setText("Resumen");

        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setLineWrap(true);
        jTextAreaResumen.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelidAnio)
                    .addComponent(jLabelDirector)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelidPelicula)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelidResumen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscarPelicula))
                            .addComponent(jScrollPane1)
                            .addComponent(jTextAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(TextFieldDirector)))
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrearPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonActualizarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonLimpiarCampos)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelidPelicula)
                    .addComponent(jTextFieldIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelidResumen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelidAnio)
                    .addComponent(jTextAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirector)
                    .addComponent(TextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearPelicula)
                    .addComponent(botonActualizarPelicula)
                    .addComponent(botonEliminarPelicula)
                    .addComponent(botonLimpiarCampos))
                .addGap(3, 3, 3)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPeliculaActionPerformed
        // TODO add your handling code here:
        eliminarPelicula();
        limpiarCampos();
    }//GEN-LAST:event_botonEliminarPeliculaActionPerformed

    private void botonCrearPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPeliculaActionPerformed
        // TODO add your handling code here:
        crearPelicula();

    }//GEN-LAST:event_botonCrearPeliculaActionPerformed

    private void botonBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPeliculaActionPerformed
        // TODO add your handling code here:
        buscarPorIdPelicula();
    }//GEN-LAST:event_botonBuscarPeliculaActionPerformed

    private void botonActualizarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPeliculaActionPerformed
        // TODO add your handling code here:
        actualizarPelicula();
    }//GEN-LAST:event_botonActualizarPeliculaActionPerformed

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        limpiarmensaje();
    }//GEN-LAST:event_botonLimpiarCamposActionPerformed
    public void limpiarmensaje() {
        mensaje.setText("");
    }

    public void limpiarCampos() {
        jTextFieldIdPelicula.setText("");
        jTextFieldTitulo.setText("");
        jTextAreaResumen.setText("");
        jTextAnio.setText("");
        TextFieldDirector.setText("");
    }

    private void buscarPorIdPelicula() {
        limpiarmensaje();
        Optional<Pelicula> optionalPelicula = pel.findById(Integer.parseInt(jTextFieldIdPelicula.getText()));
       
        if (optionalPelicula.isPresent()) {
            
            Pelicula pelicula = optionalPelicula.get();
            jTextFieldTitulo.setText(pelicula.getTitulo());
            jTextAreaResumen.setText(pelicula.getResumen());
            jTextAnio.setText(Integer.toString(pelicula.getAnio()));
            TextFieldDirector.setText(pelicula.getDirector());
            
        } else {
            
            limpiarCampos();
            mensaje.setText("Lo sentimos, aún no está disponible en Redflix");
        }
    }

    private void crearPelicula() {
        Optional<Pelicula> optionalPelicula = pel.findById(Integer.parseInt(jTextFieldIdPelicula.getText()));
       
        if (optionalPelicula.isPresent()) {
            
            mensaje.setText("El Id de la película ya fue asignado, debe usar otro");
            
        } else {
            
            Pelicula pelicula = new Pelicula();
            pelicula.setId_pelicula(Integer.parseInt(jTextFieldIdPelicula.getText()));
            pelicula.setTitulo(jTextFieldTitulo.getText());
            pelicula.setResumen(jTextAreaResumen.getText());
            pelicula.setAnio(Integer.parseInt(jTextAnio.getText()));
            pelicula.setDirector(TextFieldDirector.getText());

            try {
                pel.save(pelicula);
                mensaje.setText("Película " + jTextFieldTitulo.getText() + " creada satisfactoriamente"); //muestra un mensaje con el nombre de la pelicua insertada
            } catch (Exception e) {
                mensaje.setText("No se pudo crear la pelicula " + jTextFieldTitulo.getText());
            }
            
            limpiarCampos();
        }
    }

    private void actualizarPelicula() {
        Pelicula pelicula = new Pelicula();
        pelicula.setId_pelicula(Integer.parseInt(jTextFieldIdPelicula.getText()));
        pelicula.setTitulo(jTextFieldTitulo.getText());
        pelicula.setResumen(jTextAreaResumen.getText());
        pelicula.setAnio(Integer.parseInt(jTextAnio.getText()));
        pelicula.setDirector(TextFieldDirector.getText());
        try {
            pel.save(pelicula);
            mensaje.setText("Película " + jTextFieldTitulo.getText() + " actualizada satisfactoriamente"); //muestra un mensaje con el nombre de la pelicua insertada
        } catch (Exception e) {
            mensaje.setText("No se pudo actualizar la pelicula " + jTextFieldTitulo.getText());
        }
        limpiarCampos();

    }

    private void eliminarPelicula() {

        int id = Integer.parseInt(jTextFieldIdPelicula.getText());

        try {
            pel.deleteById(id);

            mensaje.setText("Se eliminó la película con Id: " + id);
        } catch (Exception e) {
            mensaje.setText("Ocurrio un error al eliminar");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliculaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliculaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldDirector;
    private javax.swing.JButton botonActualizarPelicula;
    private javax.swing.JButton botonBuscarPelicula;
    private javax.swing.JButton botonCrearPelicula;
    private javax.swing.JButton botonEliminarPelicula;
    private javax.swing.JButton botonLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelidAnio;
    private javax.swing.JLabel jLabelidPelicula;
    private javax.swing.JLabel jLabelidResumen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAnio;
    private javax.swing.JTextArea jTextAreaResumen;
    private javax.swing.JTextField jTextFieldIdPelicula;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
